### ISSUE TITLE
Un sistema de envío automatizado de emails a los taxistas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil_Taxis#18]
Un sistema de envío automatizado de emails a los taxistas. Que el administrador 
pueda, pulsando un botón, enviar emails a todos los taxistas de las bases
con los transportes que tienen asignados para el día siguiente.

(Se entiende aquí que cada base tiene solo una dirección de email y un
taxista. Si ese taxista a su vez tiene que repartir los transportes, no nos
incumbe).

**Comment by PaulJBis** [comment]
En la web de pruebas ya. Hay que probarlo.

**Comment by PaulJBis** [comment]
Bases con emails: Castrojeriz y Santiago.

**Comment by PaulJBis** [comment]
He probado a añadir dos emails a dos bases. Al pulsar el botón, veo que se hace un POST a /admin/bases/emailsend, pero no pasa nada más, y los emails no llegan.

**Comment by Raimond82** [comment]
Lo tenía puesto para que me los mandara a mi mientras no teníamos ningún email. Ya lo he cambiado y deberían haber llegado a los dos correos que hay disponibles.

En la columna estado, una vez que le damos a enviar, debería aparecer el estado del envío (Enviado/Falló/No Email), pero de momento eso no lo hace. Lo meteré en breve

También hay la posibilidad de notificar sólo a una base en concreto. El botón se activa cuando la base tiene email asociado.

**Comment by PaulJBis** [comment]
Lo que sí que habría que añadir a los emails es la información de la hora a la que recoger a los pasajeros, que se nos había olvidado.

**Comment by PaulJBis** [comment]
Confirmo: hace falta que se vea el estado del pedido; por tanto, tiene que salir ahí el significado, no solamente un "0" o un "1". No hace falta que aparezca el precio.

**Comment by PaulJBis** [comment]
OK. Pendiente de hablar con el cliente para aprobación final.

**Comment by PaulJBis** [comment]
Una duda: en la BD hay un campo en las reservas llamado "notas_pago". ¿Se utiliza para algo? ¿Por qué no aparece en la UI para "modificar reserva"?

Lo pregunto porque podría ser útil para un tema que hemos estado discutiendo con el cliente estos días.

**Comment by PaulJBis** [comment]
Decidido. Se va a usar "notas_pago" para esta finalidad. En la página de admin., debería haber sobre este campo un aviso: "este campo no se muestra al transportista".

**Comment by PaulJBis** [comment]
Hecho. En los emails no se envían las notas privadas... pero tampoco las otras. Los campos "notas cliente" y "notas admin." salen vacíos, incluso cuando hay texto en ellos.

**Comment by PaulJBis** [comment]
Corregido.
