### ISSUE TITLE
Error 500 cuando se redirige al TPV en algunas rutas concretas

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil_Taxis#2]
Si ponemos como origen "Aeropuerto efe Biarritz", y destino "Saint-Jean pied-de Port", al hacer el pedido, cuando nos debería redirigir al TPV nos da un error 500.

**Comment by PaulJBis** [comment]
Por curiosidad, ¿qué pasaba aquí? ¿Por qué daba error solo en rutas como estas?

**Comment by PaulJBis** [comment]
(He comprobado que estaba arreglado, por cierto. Es solo curiosidad).

**Comment by Raimond82** [comment]
Lo que pasaba es que al quitar una de las tarifas de Francia cambié los nombres de las tarifas de tarifa_fr1 y tarifa_fr2 a tarifa_fr, y se me coló un tarifa_fr1 en el código, pero esa tarifa ahora ya no existe y no podía calcularla.
