### ISSUE TITLE
El TPV no funciona en inglés

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil_Taxis#22]
Si probamos a hacer una compra en inglés en la web de taxis, al intentar redirigirnos al TPV virtual nos da un "Internal server error".

En la web de pruebas, al hacer el pedido, nos aparece un error de Symfony:

The requested language "en" was not available. Available languages: "es, es"
406 Not Acceptable - NotAcceptableLanguageException 

Stack Trace

in app/cache/dev/classes.php at line 8057  -
  ```
      $params['_route'], $this->hostMap[$currentLocale], implode(', ', $availableHosts)));
        }
        }
        throw new NotAcceptableLanguageException($currentLocale, $params['_locales']);
        }
        unset($params['_locales']);
        $params['_locale'] = $currentLocale;

```

**Comment by PaulJBis** [comment]
En realidad, en la web de pruebas da este error de Symfony en todos los idiomas excepto en castellano. En cambio, en la web de producción solo falla en inglés.

**Comment by Raimond82** [comment]
El problema estaba en las traducciones de las rutas. El formulario no las usaba.

Además el tpv solo acepta una url en su configuración. Modificado el controlador para que no traduzca las rutas que tienen que ver con el tpv.

Subido a desarrollo

**Comment by PaulJBis** [comment]
Subido a pruebas. Parece que funciona.

**Comment by PaulJBis** [comment]
Probado en producción.
