### ISSUE TITLE
Los usuarios logeados de la web principal no aparecen como logeados en la de taxis

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil_Taxis#6]
Al estar en el mismo dominio y usar la misma base de datos de clientes, lo ideal sería que el usuario que haya hecho login en la web principal pueda aparecer también como "logeado" en la de taxis. Pero esto no sucede.

(Especialmente relevante porque no hay un formulario de login separado para la web de taxis; redirige al de la web principal).

**Comment by Raimond82** [comment]
Para solucionar tanto esto, como el bug #5 hay que hacer un pequeño cambio en las cookies de la web principal. Ahora mismo las cookies se generan sólo para el subdominio en que se encuentran. Hay que hacer que se creen para todo el dominio. Primero hay que hacer el cambio en el dominio principal y luego modificar taxi

**Comment by PaulJBis** [comment]
OK. Cuando lo haga te aviso.

**Comment by Raimond82** [comment]
Ya está listo. Lo subí al git y a pruebas.

Avisame cuando lo subas para hacer pruebas en taxi

**Comment by PaulJBis** [comment]
Resuelto.
