### ISSUE TITLE
Admin.: mapa de Google Maps no saca la ruta correctamente

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/Caminofacil_Taxis#7]
En la página de admin., al crear una reserva nueva, el botón de "Ver en Google Maps" no muestra la misma ruta que está usando el sistema para calcular.

Lo que ocurre, por lo visto, es que Google Maps hace el cálculo siempre por la ruta más rápida, no la más corta, tal como tenemos programado. Habría que buscar alguna forma de pasarle por la URL los mismos parámetros que usamos para calcular la ruta internamente.

**Comment by PaulJBis** [comment]
Añadido fix. Por probar.

**Comment by PaulJBis** [comment]
El botón de "Ver mapa base" no sale nunca. En todas las pruebas que he hecho (tanto en rutas que parten de una base como en rutas que no), sale sólo el botón de "Ver en Google Maps".

**Comment by Raimond82** [comment]
https://taxi.caminofacil.net/admin/reserva/68

**Comment by PaulJBis** [comment]
¿Pero tienes que hacer la reserva? Yo estoy probando simplemente en la página de "Añadir reserva", sin hacerla:

![untitled-1](https://user-images.githubusercontent.com/7503165/44392920-a2ea9d80-a533-11e8-8249-bee4ab9b9b53.png)

![untitled-2](https://user-images.githubusercontent.com/7503165/44392929-a7af5180-a533-11e8-8acb-91d0f8bd5c6c.png)

**Comment by Raimond82** [comment]
Ok. En la pagina de añadir reserva no está modificado, sólo al editar reserva. Pruébalo y si el sistema te parece bien así, lo preparo también para la zona de añadir reserva
